### ISSUE TITLE
Undersøk mulighetene for og verdien i å enhetsteste Sass-funksjoner og mixins med True

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3189]
- https://www.npmjs.com/package/sass-true
- https://www.educative.io/blog/sass-tutorial-unit-testing-with-sass-true

Biblioteket av Sass-mixins og funksjoner i Core vokser, men vi har ikke noen automatiserte tester (utover visuelle regresjonstester). True er et interessant verktøy for å skrive enhetstester for Sass-kode. Gjør et eksperiment og se om det gir mening å ta i bruk i Jøkul for regresjonstester.

**Comment by wkillerud** [comment]
Har satt opp et testoppsett i https://github.com/fremtind/jokul/commit/6a33c5addd680601ae1a2e815e790cf59c5854f1

Kjører fint via Jest, og feiler når det skal. Eksempel på output når jeg sendte inn 15px i stedet for 16px:

```
 FAIL  ./sass-true.test.ts
  ● Sass › rem [function] › calculates the expected 1rem value from the base value 16px

    assert.fail(received, expected)

    Message:
      calculates the expected 1rem value from the base value 16px [type: assert-equal]
    
    - Expected
    + Received
    
    - [number] 1rem
    + [number] 0.9375rem
    

      at node_modules/sass-true/src/index.ts:115:20
      at arrayEach (node_modules/lodash/lodash.js:530:11)
      at forEach (node_modules/lodash/lodash.js:9410:14)
      at Object.<anonymous> (node_modules/sass-true/src/index.ts:113:16)

Test Suites: 1 failed, 6 passed, 7 total
```

Tror dette kan være verdt å ta inn, eller hva @piofinn ?
